from setuptools import setup, find_packages

setup(
    name='ascon_kat',
    version='0.1.0',
    description='A package for accessing KAT vectors generated by Ascon reference implementations.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Alexandre Menu',
    author_email='alexandre.menu@emse.fr',
    package_dir={'': 'src'},
    packages=find_packages(where='src'),
    python_requires='>=3.7',
)
